version: '1'
build:
  env:
    - NODE_ENV=production
  steps:
    - name: install
      command: npm ci
      env:
        - NODE_ENV=production
    - name: build
      command: npm run build
  output: dist
release:
  command: npm start
  env:
    - NODE_ENV=production
  automaticPort: true